// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(customer_id)
VALUES ($1)
RETURNING id, order_number, customer_id, order_date, status, total_amount
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int32) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderDate,
		&i.Status,
		&i.TotalAmount,
	)
	return i, err
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, order_number, customer_id, status, total_amount::text, order_date
FROM orders
WHERE id = $1
`

type GetOrderByIdRow struct {
	ID          int32
	OrderNumber string
	CustomerID  int32
	Status      OrderStatus
	TotalAmount string
	OrderDate   pgtype.Timestamptz
}

func (q *Queries) GetOrderById(ctx context.Context, id int32) (GetOrderByIdRow, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i GetOrderByIdRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.Status,
		&i.TotalAmount,
		&i.OrderDate,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT oi.id,
       oi.product_id,
       p.name              AS product_name,
       oi.quantity,
       oi.unit_price::text AS unit_price,
       oi.line_total::text AS line_total
FROM order_item oi
         JOIN product p ON oi.product_id = p.id
WHERE oi.order_id = $1
`

type GetOrderItemsRow struct {
	ID          int32
	ProductID   int32
	ProductName string
	Quantity    int32
	UnitPrice   string
	LineTotal   string
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID int32) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, order_number, status, total_amount::text, order_date
FROM orders
ORDER BY order_date DESC
`

type ListOrdersRow struct {
	ID          int32
	OrderNumber string
	Status      OrderStatus
	TotalAmount string
	OrderDate   pgtype.Timestamptz
}

func (q *Queries) ListOrders(ctx context.Context) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Status,
			&i.TotalAmount,
			&i.OrderDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, order_number, status, total_amount::text, order_date
FROM orders
WHERE customer_id = $1
ORDER BY order_date DESC
`

type ListOrdersByCustomerRow struct {
	ID          int32
	OrderNumber string
	Status      OrderStatus
	TotalAmount string
	OrderDate   pgtype.Timestamptz
}

func (q *Queries) ListOrdersByCustomer(ctx context.Context, customerID int32) ([]ListOrdersByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByCustomerRow
	for rows.Next() {
		var i ListOrdersByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Status,
			&i.TotalAmount,
			&i.OrderDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderTotalAmount = `-- name: SetOrderTotalAmount :one
UPDATE orders
SET total_amount = $1
WHERE id = $2
RETURNING id, order_number, customer_id, order_date, status, total_amount
`

type SetOrderTotalAmountParams struct {
	TotalAmount pgtype.Numeric
	ID          int32
}

func (q *Queries) SetOrderTotalAmount(ctx context.Context, arg SetOrderTotalAmountParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderTotalAmount, arg.TotalAmount, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderDate,
		&i.Status,
		&i.TotalAmount,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int32
	Status OrderStatus
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
