// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_movements.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movement (
    product_id,
    quantity_change,
    movement_type,
    related_order_id,
    reason,
    employee_id
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, quantity_change, movement_type, related_order_id, reason, created_at, employee_id
`

type CreateStockMovementParams struct {
	ProductID      int32
	QuantityChange int32
	MovementType   MovementType
	RelatedOrderID pgtype.Int4
	Reason         pgtype.Text
	EmployeeID     pgtype.Int4
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.ProductID,
		arg.QuantityChange,
		arg.MovementType,
		arg.RelatedOrderID,
		arg.Reason,
		arg.EmployeeID,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.QuantityChange,
		&i.MovementType,
		&i.RelatedOrderID,
		&i.Reason,
		&i.CreatedAt,
		&i.EmployeeID,
	)
	return i, err
}

const getStockForUpdate = `-- name: GetStockForUpdate :one
SELECT id, product_id, quantity, min_quantity
FROM stock
WHERE product_id = $1
    FOR UPDATE
`

func (q *Queries) GetStockForUpdate(ctx context.Context, productID int32) (Stock, error) {
	row := q.db.QueryRow(ctx, getStockForUpdate, productID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Quantity,
		&i.MinQuantity,
	)
	return i, err
}

const listStockMovements = `-- name: ListStockMovements :many
SELECT id, product_id, quantity_change, movement_type, related_order_id, reason, created_at, employee_id
FROM stock_movement
ORDER BY created_at DESC
`

func (q *Queries) ListStockMovements(ctx context.Context) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listStockMovements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.QuantityChange,
			&i.MovementType,
			&i.RelatedOrderID,
			&i.Reason,
			&i.CreatedAt,
			&i.EmployeeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStockQuantity = `-- name: UpdateStockQuantity :exec
UPDATE stock
SET quantity = $2
WHERE product_id = $1
`

type UpdateStockQuantityParams struct {
	ProductID int32
	Quantity  int32
}

func (q *Queries) UpdateStockQuantity(ctx context.Context, arg UpdateStockQuantityParams) error {
	_, err := q.db.Exec(ctx, updateStockQuantity, arg.ProductID, arg.Quantity)
	return err
}
