@baseUrl = http://localhost:8081/api/v1
@JWT_TOKEN = put_your_access_token_here
@REFRESH_TOKEN = put_your_refresh_token_here

POST {{baseUrl}}/auth/register-company
Content-Type: application/json

{
  "name": "Mleczko Sp. z o.o.",
  "taxId": "123456789",
  "mainEmail": "contact@mleczko.pl",
  "phoneNumber": "+48123456789",
  "addresses": [
    {
      "address": "ul. ulica 10",
      "city": "Miasto",
      "postalCode": "11-234",
      "country": "Poland",
      "type": "BILLING"
    },
    {
      "address": "ul. ulica 5",
      "city": "Inne miasto",
      "postalCode": "36-127",
      "country": "Poland",
      "type": "SHIPPING"
    }
  ],
  "email": "szef@mleczko.pl",
  "password": "mleczko"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@mleczarnia.dev",
  "password": "mleczko...mmmm"
}

###
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{REFRESH_TOKEN}}"
}

###
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{REFRESH_TOKEN}}"
}

###
GET {{baseUrl}}/me
Authorization: Bearer {{JWT_TOKEN}}

###
PATCH {{baseUrl}}/me/change-password
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
  "currentPassword": "mleczko...mmmm",
  "newPassword": "śmietanka"
}

