// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company_address.sql

package sqlc

import (
	"context"
)

const createCompanyAddress = `-- name: CreateCompanyAddress :one
INSERT INTO company_address (customer_company_id, address_line, city, postal_code, country, type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, customer_company_id, address_line, city, postal_code, country, type
`

type CreateCompanyAddressParams struct {
	CustomerCompanyID int32
	AddressLine       string
	City              string
	PostalCode        string
	Country           string
	Type              AddressType
}

func (q *Queries) CreateCompanyAddress(ctx context.Context, arg CreateCompanyAddressParams) (CompanyAddress, error) {
	row := q.db.QueryRow(ctx, createCompanyAddress,
		arg.CustomerCompanyID,
		arg.AddressLine,
		arg.City,
		arg.PostalCode,
		arg.Country,
		arg.Type,
	)
	var i CompanyAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerCompanyID,
		&i.AddressLine,
		&i.City,
		&i.PostalCode,
		&i.Country,
		&i.Type,
	)
	return i, err
}
