// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompanyDetailsById = `-- name: GetCompanyDetailsById :one
SELECT c.id,
       c.name,
       c.tax_id,
       c.main_email,
       c.phone,
       CASE
           WHEN c.at_risk IS TRUE THEN 'AT_RISK'
           WHEN c.is_active IS TRUE THEN 'ACTIVE'
           ELSE 'INACTIVE'
           END::company_status                                                          AS status,
       c.created_at,
       count(o.id) FILTER (WHERE o.status != 'CANCELLED')                               AS order_count,
       coalesce(sum(o.total_amount) FILTER (WHERE o.status != 'CANCELLED'), 0)::text AS total_orders_value,
       count(o.id) FILTER (WHERE o.status = 'SHIPPED')                                  AS completed_orders
FROM customer_company AS c
         LEFT JOIN orders AS o ON (o.customer_id = c.id)
WHERE c.id = $1
GROUP BY c.id
`

type GetCompanyDetailsByIdRow struct {
	ID               int32
	Name             string
	TaxID            string
	MainEmail        string
	Phone            pgtype.Text
	Status           CompanyStatus
	CreatedAt        pgtype.Timestamp
	OrderCount       int64
	TotalOrdersValue string
	CompletedOrders  int64
}

func (q *Queries) GetCompanyDetailsById(ctx context.Context, id int32) (GetCompanyDetailsByIdRow, error) {
	row := q.db.QueryRow(ctx, getCompanyDetailsById, id)
	var i GetCompanyDetailsByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TaxID,
		&i.MainEmail,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.OrderCount,
		&i.TotalOrdersValue,
		&i.CompletedOrders,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT c.id,
       c.name,
       c.tax_id,
       c.main_email,
       c.phone,
       CASE
           WHEN c.at_risk IS TRUE THEN 'AT_RISK'
           WHEN c.is_active IS TRUE THEN 'ACTIVE'
           ELSE 'INACTIVE'
           END::company_status                            AS status,
       c.created_at,
       COUNT(o.id) FILTER (WHERE o.status != 'CANCELLED') AS order_count
FROM customer_company AS c
         LEFT JOIN orders AS o ON (o.customer_id = c.id)
group by c.id
`

type ListCompaniesRow struct {
	ID         int32
	Name       string
	TaxID      string
	MainEmail  string
	Phone      pgtype.Text
	Status     CompanyStatus
	CreatedAt  pgtype.Timestamp
	OrderCount int64
}

func (q *Queries) ListCompanies(ctx context.Context) ([]ListCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesRow
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TaxID,
			&i.MainEmail,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.OrderCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
