// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_company.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerCompany = `-- name: CreateCustomerCompany :one
INSERT INTO customer_company (name, tax_id, main_email, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, name, tax_id, main_email, phone, is_active, at_risk, created_at
`

type CreateCustomerCompanyParams struct {
	Name      string
	TaxID     string
	MainEmail string
	Phone     pgtype.Text
}

func (q *Queries) CreateCustomerCompany(ctx context.Context, arg CreateCustomerCompanyParams) (CustomerCompany, error) {
	row := q.db.QueryRow(ctx, createCustomerCompany,
		arg.Name,
		arg.TaxID,
		arg.MainEmail,
		arg.Phone,
	)
	var i CustomerCompany
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TaxID,
		&i.MainEmail,
		&i.Phone,
		&i.IsActive,
		&i.AtRisk,
		&i.CreatedAt,
	)
	return i, err
}
