// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employee (first_name, last_name, position, hire_date)
VALUES ($1, $2, $3, $4)
RETURNING id, first_name, last_name, position, is_active, hire_date
`

type CreateEmployeeParams struct {
	FirstName string
	LastName  string
	Position  string
	HireDate  pgtype.Timestamp
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.FirstName,
		arg.LastName,
		arg.Position,
		arg.HireDate,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.IsActive,
		&i.HireDate,
	)
	return i, err
}

const getEmployeeById = `-- name: GetEmployeeById :one
SELECT id, first_name, last_name, position, is_active, hire_date
FROM employee
WHERE id = $1
`

func (q *Queries) GetEmployeeById(ctx context.Context, id int32) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeById, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.IsActive,
		&i.HireDate,
	)
	return i, err
}
