// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoice (order_id,
                     issue_date,
                     due_date,
                     total_amount,
                     status)
VALUES ($1, $2,  $3, $4, 'UNPAID')
RETURNING id, order_id, invoice_number, issue_date, due_date, total_amount, status
`

type CreateInvoiceParams struct {
	OrderID     int32
	IssueDate   pgtype.Timestamptz
	DueDate     pgtype.Timestamptz
	TotalAmount pgtype.Numeric
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.OrderID,
		arg.IssueDate,
		arg.DueDate,
		arg.TotalAmount,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.Status,
	)
	return i, err
}

const getInvoiceById = `-- name: GetInvoiceById :one
SELECT id, order_id, invoice_number, issue_date, due_date, total_amount, status
FROM invoice
WHERE id = $1
`

func (q *Queries) GetInvoiceById(ctx context.Context, id int32) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceById, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.Status,
	)
	return i, err
}

const getInvoiceItems = `-- name: GetInvoiceItems :many
SELECT oi.quantity,
       oi.unit_price::text AS unit_price,
       oi.line_total::text AS line_total,
       p.name              AS product_name,
       p.unit
FROM order_item oi
         JOIN product p ON p.id = oi.product_id
WHERE oi.order_id = $1
`

type GetInvoiceItemsRow struct {
	Quantity    int32
	UnitPrice   string
	LineTotal   string
	ProductName string
	Unit        string
}

func (q *Queries) GetInvoiceItems(ctx context.Context, orderID int32) ([]GetInvoiceItemsRow, error) {
	rows, err := q.db.Query(ctx, getInvoiceItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvoiceItemsRow
	for rows.Next() {
		var i GetInvoiceItemsRow
		if err := rows.Scan(
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.ProductName,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoiceWithOrder = `-- name: GetInvoiceWithOrder :one
SELECT i.id, i.order_id, i.invoice_number, i.issue_date, i.due_date, i.total_amount, i.status,
       i.total_amount::text AS total_amount_str,
       o.order_number,
       o.order_date,
       c.name               AS company_name,
       c.tax_id,
       c.main_email,
       c.id                 AS customer_id
FROM invoice i
         JOIN orders o ON o.id = i.order_id
         JOIN customer_company c ON c.id = o.customer_id
WHERE i.id = $1
`

type GetInvoiceWithOrderRow struct {
	ID             int32
	OrderID        int32
	InvoiceNumber  string
	IssueDate      pgtype.Timestamptz
	DueDate        pgtype.Timestamptz
	TotalAmount    pgtype.Numeric
	Status         InvoiceStatus
	TotalAmountStr string
	OrderNumber    string
	OrderDate      pgtype.Timestamptz
	CompanyName    string
	TaxID          string
	MainEmail      string
	CustomerID     int32
}

func (q *Queries) GetInvoiceWithOrder(ctx context.Context, id int32) (GetInvoiceWithOrderRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceWithOrder, id)
	var i GetInvoiceWithOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.Status,
		&i.TotalAmountStr,
		&i.OrderNumber,
		&i.OrderDate,
		&i.CompanyName,
		&i.TaxID,
		&i.MainEmail,
		&i.CustomerID,
	)
	return i, err
}

const invoiceExistsForOrder = `-- name: InvoiceExistsForOrder :one
SELECT EXISTS (SELECT 1
               FROM invoice
               WHERE order_id = $1)
`

func (q *Queries) InvoiceExistsForOrder(ctx context.Context, orderID int32) (bool, error) {
	row := q.db.QueryRow(ctx, invoiceExistsForOrder, orderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT i.id,
       i.invoice_number,
       i.issue_date,
       i.due_date,
       i.total_amount::text AS total_amount,
       i.status,
       o.id                 AS order_id,
       c.name               AS company_name
FROM invoice i
         JOIN orders o ON o.id = i.order_id
         JOIN customer_company c ON c.id = o.customer_id
ORDER BY i.issue_date DESC
`

type ListInvoicesRow struct {
	ID            int32
	InvoiceNumber string
	IssueDate     pgtype.Timestamptz
	DueDate       pgtype.Timestamptz
	TotalAmount   string
	Status        InvoiceStatus
	OrderID       int32
	CompanyName   string
}

func (q *Queries) ListInvoices(ctx context.Context) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesRow
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.IssueDate,
			&i.DueDate,
			&i.TotalAmount,
			&i.Status,
			&i.OrderID,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesForCompany = `-- name: ListInvoicesForCompany :many
SELECT i.id,
       i.invoice_number,
       i.issue_date,
       i.due_date,
       i.total_amount::text AS total_amount,
       i.status,
       o.id                 AS order_id
FROM invoice i
         JOIN orders o ON o.id = i.order_id
WHERE o.customer_id = $1
ORDER BY i.issue_date DESC
`

type ListInvoicesForCompanyRow struct {
	ID            int32
	InvoiceNumber string
	IssueDate     pgtype.Timestamptz
	DueDate       pgtype.Timestamptz
	TotalAmount   string
	Status        InvoiceStatus
	OrderID       int32
}

func (q *Queries) ListInvoicesForCompany(ctx context.Context, customerID int32) ([]ListInvoicesForCompanyRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesForCompany, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesForCompanyRow
	for rows.Next() {
		var i ListInvoicesForCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.IssueDate,
			&i.DueDate,
			&i.TotalAmount,
			&i.Status,
			&i.OrderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoice
SET status = $2
WHERE id = $1
RETURNING id, order_id, invoice_number, issue_date, due_date, total_amount, status
`

type UpdateInvoiceStatusParams struct {
	ID     int32
	Status InvoiceStatus
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.Status,
	)
	return i, err
}
