// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeUNSPECIFIED     AccountType = "UNSPECIFIED"
	AccountTypeCUSTOMERCOMPANY AccountType = "CUSTOMER_COMPANY"
	AccountTypeEMPLOYEE        AccountType = "EMPLOYEE"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType
	Valid       bool // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type AddressType string

const (
	AddressTypeBILLING  AddressType = "BILLING"
	AddressTypeSHIPPING AddressType = "SHIPPING"
)

func (e *AddressType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AddressType(s)
	case string:
		*e = AddressType(s)
	default:
		return fmt.Errorf("unsupported scan type for AddressType: %T", src)
	}
	return nil
}

type NullAddressType struct {
	AddressType AddressType
	Valid       bool // Valid is true if AddressType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAddressType) Scan(value interface{}) error {
	if value == nil {
		ns.AddressType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AddressType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAddressType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AddressType), nil
}

type CompanyStatus string

const (
	CompanyStatusACTIVE   CompanyStatus = "ACTIVE"
	CompanyStatusINACTIVE CompanyStatus = "INACTIVE"
	CompanyStatusATRISK   CompanyStatus = "AT_RISK"
)

func (e *CompanyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyStatus(s)
	case string:
		*e = CompanyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyStatus: %T", src)
	}
	return nil
}

type NullCompanyStatus struct {
	CompanyStatus CompanyStatus
	Valid         bool // Valid is true if CompanyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyStatus), nil
}

type OrderStatus string

const (
	OrderStatusNEW           OrderStatus = "NEW"
	OrderStatusINVOICED      OrderStatus = "INVOICED"
	OrderStatusINPREPARATION OrderStatus = "IN_PREPARATION"
	OrderStatusCANCELLED     OrderStatus = "CANCELLED"
	OrderStatusSHIPPED       OrderStatus = "SHIPPED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Role string

const (
	RoleADMIN     Role = "ADMIN"
	RoleSTAFF     Role = "STAFF"
	RoleWAREHOUSE Role = "WAREHOUSE"
	RoleCLIENT    Role = "CLIENT"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type UserStatus string

const (
	UserStatusACTIVE   UserStatus = "ACTIVE"
	UserStatusBLOCKED  UserStatus = "BLOCKED"
	UserStatusINACTIVE UserStatus = "INACTIVE"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type CompanyAddress struct {
	ID                int32
	CustomerCompanyID int32
	AddressLine       string
	City              string
	PostalCode        string
	Country           string
	Type              AddressType
}

type CustomerCompany struct {
	ID        int32
	Name      string
	TaxID     string
	MainEmail string
	Phone     pgtype.Text
	IsActive  bool
	AtRisk    bool
	CreatedAt pgtype.Timestamp
}

type Employee struct {
	ID        int32
	FirstName string
	LastName  string
	Position  string
	IsActive  bool
	HireDate  pgtype.Timestamp
}

type Order struct {
	ID          int32
	OrderNumber string
	CustomerID  int32
	OrderDate   pgtype.Timestamptz
	Status      OrderStatus
	TotalAmount pgtype.Numeric
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    int32
	Token     string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
	CreatedAt pgtype.Timestamptz
}

type UserAccount struct {
	ID                int32
	Email             string
	PasswordHash      string
	Role              Role
	IsActive          bool
	IsBlocked         bool
	LastLoginAt       pgtype.Timestamptz
	CustomerCompanyID pgtype.Int4
	EmployeeID        pgtype.Int4
	PasswordChangedAt pgtype.Timestamptz
}
