// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Role string

const (
	RoleADMIN     Role = "ADMIN"
	RoleSTAFF     Role = "STAFF"
	RoleWAREHOUSE Role = "WAREHOUSE"
	RoleCLIENT    Role = "CLIENT"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    int32
	Token     string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
	CreatedAt pgtype.Timestamptz
}

type UserAccount struct {
	ID                int32
	Email             string
	PasswordHash      string
	Role              Role
	IsActive          bool
	LastLoginAt       pgtype.Timestamptz
	CustomerCompanyID pgtype.Int4
	EmployeeID        pgtype.Int4
	PasswordChangedAt pgtype.Timestamptz
}
