// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_item.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOrderItem = `-- name: InsertOrderItem :one
INSERT INTO order_item(order_id, product_id, quantity, unit_price, line_total)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_id, quantity, unit_price, line_total
`

type InsertOrderItemParams struct {
	OrderID   int32
	ProductID int32
	Quantity  int32
	UnitPrice pgtype.Numeric
	LineTotal pgtype.Numeric
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, insertOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
	)
	return i, err
}
