// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateProduct = `-- name: ActivateProduct :one
UPDATE product
SET is_active = true
WHERE id = $1
RETURNING id, name, category, unit, default_price, is_active
`

func (q *Queries) ActivateProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, activateProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.DefaultPrice,
		&i.IsActive,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (name, category, unit, default_price)
VALUES ($1, $2, $3, $4)
RETURNING id, name, category, unit, default_price, is_active
`

type CreateProductParams struct {
	Name         string
	Category     string
	Unit         string
	DefaultPrice pgtype.Numeric
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Category,
		arg.Unit,
		arg.DefaultPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.DefaultPrice,
		&i.IsActive,
	)
	return i, err
}

const deactivateProduct = `-- name: DeactivateProduct :one
UPDATE product
SET is_active = false
WHERE id = $1
RETURNING id, name, category, unit, default_price, is_active
`

func (q *Queries) DeactivateProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, deactivateProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.DefaultPrice,
		&i.IsActive,
	)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT p.id, p.name, p.category, p.unit, p.default_price, p.is_active,
       p.default_price::text                                                    AS default_price_text,
       coalesce(s.quantity, 0),
       coalesce(s.min_quantity, 0),
       coalesce(count(m.id) FILTER (WHERE m.movement_type = 'LOSS'), 0)::int4   AS damaged_count,
       coalesce(count(m.id) FILTER (WHERE m.movement_type = 'RETURN'), 0)::int4 AS return_count
FROM product p
         LEFT JOIN stock s ON p.id = s.product_id
         LEFT JOIN stock_movement m ON p.id = m.product_id
WHERE p.id = $1
GROUP BY p.id, p.name
ORDER BY p.name
`

type GetProductByIdRow struct {
	ID               int32
	Name             string
	Category         string
	Unit             string
	DefaultPrice     pgtype.Numeric
	IsActive         bool
	DefaultPriceText string
	Quantity         int32
	MinQuantity      int32
	DamagedCount     int32
	ReturnCount      int32
}

func (q *Queries) GetProductById(ctx context.Context, id int32) (GetProductByIdRow, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i GetProductByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.DefaultPrice,
		&i.IsActive,
		&i.DefaultPriceText,
		&i.Quantity,
		&i.MinQuantity,
		&i.DamagedCount,
		&i.ReturnCount,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.name, p.category, p.unit, p.default_price, p.is_active,
       p.default_price::text                                                    AS default_price_text,
       coalesce(s.quantity, 0),
       coalesce(s.min_quantity, 0),
       coalesce(count(m.id) FILTER (WHERE m.movement_type = 'LOSS'), 0)::int4   AS damaged_count,
       coalesce(count(m.id) FILTER (WHERE m.movement_type = 'RETURN'), 0)::int4 AS return_count
FROM product p
         LEFT JOIN stock s ON p.id = s.product_id
         LEFT JOIN stock_movement m ON p.id = m.product_id
GROUP BY p.id, p.name
ORDER BY p.name
`

type ListProductsRow struct {
	ID               int32
	Name             string
	Category         string
	Unit             string
	DefaultPrice     pgtype.Numeric
	IsActive         bool
	DefaultPriceText string
	Quantity         int32
	MinQuantity      int32
	DamagedCount     int32
	ReturnCount      int32
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Unit,
			&i.DefaultPrice,
			&i.IsActive,
			&i.DefaultPriceText,
			&i.Quantity,
			&i.MinQuantity,
			&i.DamagedCount,
			&i.ReturnCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product
SET name          = COALESCE($1, name),
    category      = COALESCE($2, category),
    unit          = COALESCE($3, unit),
    default_price = COALESCE($4, default_price)
WHERE id = $5
RETURNING id, name, category, unit, default_price, is_active
`

type UpdateProductParams struct {
	Name         pgtype.Text
	Category     pgtype.Text
	Unit         pgtype.Text
	DefaultPrice pgtype.Numeric
	ID           int32
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Category,
		arg.Unit,
		arg.DefaultPrice,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.DefaultPrice,
		&i.IsActive,
	)
	return i, err
}
