// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_account.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user_account (email, password_hash, role)
VALUES ($1, $2, $3) RETURNING id, email, password_hash, role, is_active, last_login_at, customer_company_id, employee_id, password_changed_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         Role
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CustomerCompanyID,
		&i.EmployeeID,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, is_active, last_login_at, customer_company_id, employee_id, password_changed_at
FROM user_account
WHERE email = $1
  AND is_active = true
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CustomerCompanyID,
		&i.EmployeeID,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, is_active, last_login_at, customer_company_id, employee_id, password_changed_at
FROM user_account
WHERE id = $1
  AND is_active = true
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CustomerCompanyID,
		&i.EmployeeID,
		&i.PasswordChangedAt,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE user_account
SET last_login_at = now()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE user_account
SET password_hash = $2,
    password_changed_at = now()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           int32
	PasswordHash string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}
