// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUsers = `-- name: ListUsers :many
SELECT CASE
           WHEN e.id IS NOT NULL THEN concat_ws(' ', e.first_name, e.last_name)
           WHEN c.id IS NOT NULL THEN c.name
           ELSE ''
           END               AS name,
       u.email,
       u.role,
       CASE
           WHEN e.id IS NOT NULL THEN 'EMPLOYEE'
           WHEN c.id IS NOT NULL THEN 'CUSTOMER_COMPANY'
           ELSE 'UNSPECIFIED'
           END::account_type as account_type,
       u.is_active,
       u.last_login_at
FROM user_account AS u
         LEFT JOIN employee AS e
                   ON (u.employee_id = e.id)
         LEFT JOIN customer_company AS c ON (u.customer_company_id = c.id)
`

type ListUsersRow struct {
	Name        string
	Email       string
	Role        Role
	AccountType AccountType
	IsActive    bool
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.Name,
			&i.Email,
			&i.Role,
			&i.AccountType,
			&i.IsActive,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
